---
# IranVault Secrets Configuration
# This file defines all secrets needed for production deployment

# JWT Secret for authentication
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: iranvault-prod
type: Opaque
data:
  # Generate with: openssl rand -base64 32
  JWT_SECRET: <BASE64_ENCODED_JWT_SECRET>
  JWT_REFRESH_SECRET: <BASE64_ENCODED_REFRESH_SECRET>

---
# Database Secrets
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: iranvault-prod
type: Opaque
data:
  POSTGRES_USER: <BASE64_ENCODED_DB_USER>
  POSTGRES_PASSWORD: <BASE64_ENCODED_DB_PASSWORD>
  POSTGRES_DB: <BASE64_ENCODED_DB_NAME>

---
# Redis Secrets
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: iranvault-prod
type: Opaque
data:
  REDIS_PASSWORD: <BASE64_ENCODED_REDIS_PASSWORD>

---
# NATS Secrets
apiVersion: v1
kind: Secret
metadata:
  name: nats-secret
  namespace: iranvault-prod
type: Opaque
data:
  NATS_USER: <BASE64_ENCODED_NATS_USER>
  NATS_PASSWORD: <BASE64_ENCODED_NATS_PASSWORD>

---
# External API Keys (for market data providers)
apiVersion: v1
kind: Secret
metadata:
  name: external-apis-secret
  namespace: iranvault-prod
type: Opaque
data:
  BINANCE_API_KEY: <BASE64_ENCODED_BINANCE_KEY>
  BINANCE_API_SECRET: <BASE64_ENCODED_BINANCE_SECRET>
  COINGECKO_API_KEY: <BASE64_ENCODED_COINGECKO_KEY>

---
# Email Service Secrets (for notifications)
apiVersion: v1
kind: Secret
metadata:
  name: email-secret
  namespace: iranvault-prod
type: Opaque
data:
  SMTP_HOST: <BASE64_ENCODED_SMTP_HOST>
  SMTP_PORT: <BASE64_ENCODED_SMTP_PORT>
  SMTP_USER: <BASE64_ENCODED_SMTP_USER>
  SMTP_PASSWORD: <BASE64_ENCODED_SMTP_PASSWORD>
  FROM_EMAIL: <BASE64_ENCODED_FROM_EMAIL>

---
# Monitoring Secrets
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secret
  namespace: iranvault-prod
type: Opaque
data:
  GRAFANA_ADMIN_PASSWORD: <BASE64_ENCODED_GRAFANA_PASSWORD>
  PROMETHEUS_USERNAME: <BASE64_ENCODED_PROMETHEUS_USER>
  PROMETHEUS_PASSWORD: <BASE64_ENCODED_PROMETHEUS_PASSWORD>

---
# TLS Certificate Secrets (for internal mTLS)
apiVersion: v1
kind: Secret
metadata:
  name: iranvault-ca
  namespace: iranvault-prod
type: Opaque
data:
  ca.crt: <BASE64_ENCODED_CA_CERT>
  ca.key: <BASE64_ENCODED_CA_KEY>

---
# Service Mesh mTLS Certificates
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-tls
  namespace: iranvault-prod
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_TLS_CERT>
  tls.key: <BASE64_ENCODED_TLS_KEY>

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-tls
  namespace: iranvault-prod
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_TLS_CERT>
  tls.key: <BASE64_ENCODED_TLS_KEY>

---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-tls
  namespace: iranvault-prod
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_TLS_CERT>
  tls.key: <BASE64_ENCODED_TLS_KEY>

---
apiVersion: v1
kind: Secret
metadata:
  name: matching-engine-tls
  namespace: iranvault-prod
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_TLS_CERT>
  tls.key: <BASE64_ENCODED_TLS_KEY>

---
# Cloud Provider Secrets (for Hetzner, AWS, etc.)
apiVersion: v1
kind: Secret
metadata:
  name: cloud-provider-secret
  namespace: iranvault-prod
type: Opaque
data:
  HETZNER_API_TOKEN: <BASE64_ENCODED_HETZNER_TOKEN>
  AWS_ACCESS_KEY_ID: <BASE64_ENCODED_AWS_KEY>
  AWS_SECRET_ACCESS_KEY: <BASE64_ENCODED_AWS_SECRET>

---
# Backup Secrets
apiVersion: v1
kind: Secret
metadata:
  name: backup-secret
  namespace: iranvault-prod
type: Opaque
data:
  BACKUP_ENCRYPTION_KEY: <BASE64_ENCODED_ENCRYPTION_KEY>
  BACKUP_STORAGE_KEY: <BASE64_ENCODED_STORAGE_KEY>
  BACKUP_STORAGE_SECRET: <BASE64_ENCODED_STORAGE_SECRET>